//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginService
    {
        public int Id { get; set; }
        public string guid { get; set; }
        public string pesel { get; set; }
        public int timestamp { get; set; }
    }
}
